/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package my.java.lib;

import org.junit.Test;
import static org.junit.Assert.*;
import my.java.lib.Foo;

public class LibraryTest {
    @Test public void someLibraryMethodReturnsTrue() {
        Foo foo = new Foo(10);
        assertTrue("Foo.val", foo.val() == 10);
        foo.set_field(15);
        assertTrue("Foo.val", foo.val() == 15);
    }
}
